from video_generator import generate_video
from uploader import upload_to_youtube

def main():
    text = "This is an automated video generated by a bot."
    video = generate_video(text, "video.mp4")
    upload_to_youtube(video, title="Hello from Bot 🚀", description=text)

if __name__ == "__main__":
    main()
